### ISSUE TITLE
mvn compile failed

### ISSUE THREAD

**Issue by sangshuduo** [inuter/Maven-Notebook#1]
mvn compile                                                                                                                                           ✔  2297  18:28:30

\[INFO\] Scanning for projects...

\[INFO\]

\[INFO\] ---------------\< com.example:build-first-maven-project >----------------

\[INFO\] Building build-first-maven-project 1.0

\[INFO\] --------------------------------\[ jar \]---------------------------------

\[INFO\]

\[INFO\] --- maven-resources-plugin:2.6:resources (default-resources) @ build-first-maven-project ---

\[WARNING\] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!

\[INFO\] skip non existing resourceDirectory /Users/sangshuduo/work/java/Maven-Notebook/build-first-maven-project/src/main/resources

\[INFO\]

\[INFO\] --- maven-compiler-plugin:3.1:compile (default-compile) @ build-first-maven-project ---

\[INFO\] Changes detected - recompiling the module!

\[WARNING\] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!

\[INFO\] Compiling 1 source file to /Users/sangshuduo/work/java/Maven-Notebook/build-first-maven-project/target/classes

\[INFO\] -------------------------------------------------------------

\[ERROR\] COMPILATION ERROR :

\[INFO\] -------------------------------------------------------------

\[ERROR\] Source option 5 is no longer supported. Use 7 or later.

\[ERROR\] Target option 5 is no longer supported. Use 7 or later.

\[INFO\] 2 errors

\[INFO\] -------------------------------------------------------------

\[INFO\] ------------------------------------------------------------------------

\[INFO\] BUILD FAILURE

\[INFO\] ------------------------------------------------------------------------

\[INFO\] Total time:  0.760 s

\[INFO\] Finished at: 2020-12-11T18:28:35+08:00

\[INFO\] ------------------------------------------------------------------------

\[ERROR\] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project build-first-maven-project: Compilation failure: Compilation failure:

\[ERROR\] Source option 5 is no longer supported. Use 7 or later.

\[ERROR\] Target option 5 is no longer supported. Use 7 or later.

\[ERROR\] -> \[Help 1\]

\[ERROR\]

\[ERROR\] To see the full stack trace of the errors, re-run Maven with the -e switch.

\[ERROR\] Re-run Maven using the -X switch to enable full debug logging.

\[ERROR\]

\[ERROR\] For more information about the errors and possible solutions, please read the following articles:

\[ERROR\] \[Help 1\] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by inuter** [comment]
两个解决方法：
1. 对于该工程，不要使用 IDEA 编译，而在 termial 手动编译；
2. 在 pom.xml 中添加如下配置：
```xml
<properties>
      <maven.compiler.source>8</maven.compiler.source>
      <maven.compiler.target>8</maven.compiler.target>
</properties>
```
